healthCareManagment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('management.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

management/urls.py
from django.urls import path

from . import views
app_name = 'frontend'
urlpatterns = [
    path('', views.home, name='index'),
    path('about-us/', views.about_us, name='about_us'),
    path('news/', views.latest_news, name='latest_news'),
    path('help/', views.WantHelp, name='want_help'),
    path('add/hospital/', views.add_hospital, name='add_hospital'),
    path('list/', views.medical_list, name='medical_list'),
    path('filter/', views.user_filter, name='user_filter'),
    path('filter-list/<str:pk>', views.filter_list, name='filter_list'),
    path('plasma/<str:pk>', views.blood_group, name='plasma'),
    path('custom-news-job', views.custom_news_job, name='news_job')
]

user/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

management/models.py
from django.db import models
from user.models import User
from user.constants import States


class Hospitals(models.Model):
    contact_info = models.CharField(max_length=20, null=False, blank=False)
    hospital_name = models.CharField(max_length=200)
    state = models.CharField(max_length=15, choices=States, default="MP")
    city = models.CharField(max_length=30, null=False, blank=False)
    total_beds = models.CharField(max_length=4, null=True, blank=True)
    oxygen_availability = models.BooleanField(default=False)
    ventilator_availability = models.BooleanField(default=False)


class Article(models.Model):
    source = models.CharField(max_length=150, null=True, blank=True)
    author = models.CharField(max_length=150, null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    url = models.CharField(max_length=500, null=True, blank=True)
    urlToImage = models.CharField(max_length=500, null=True, blank=True)
    publishedAt = models.CharField(max_length=150, null=True, blank=True)
    content = models.TextField(null=True, blank=True)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from user.constants import *


class User(models.Model):
    first_name = models.CharField(max_length=255, blank=False, null=False)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=255, blank=False, null=False)
    state = models.CharField(max_length=15, choices=States, default="MP")
    city = models.CharField(max_length=255, blank=False, null=False)
    blood_group = models.CharField(max_length=3, choices=BloodGroup, blank=True, null=True)
    oxygen_cylinder_supplier = models.BooleanField(default=False)
    plasma_donor = models.BooleanField(default=False)
    medical_supplier = models.BooleanField(default=False)
    medical_support = models.BooleanField(default=False)
    doctor = models.BooleanField(default=False)
    health_care_worker = models.BooleanField(default=False)
    additional_details = models.CharField(max_length=1000, blank=True, null=True)
    remdisivr = models.BooleanField(default=False)
    toclizumab = models.BooleanField(default=False)
    specify_other = models.CharField(max_length=255, blank=True, null=True)
    REQUIRED_FIELDS = []

    def get_fullname(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.email

    class Meta:
        unique_together = ('email', 'phone',)

management/forms.py
from django import forms
from django.forms import ModelForm
from . import models as management_models
from user import models as user_models
from user.constants import *


class AddHospital(ModelForm):
    contact_info = forms.CharField(widget=(forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'number',
        'placeholder': 'Hospital Contact Number.'
    })), required=True)
    hospital_name = forms.CharField(widget=(forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
        'placeholder': 'Enter Hospital Name.'
    })), required=True)
    city = forms.CharField(widget=(forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
        'placeholder': 'Enter City.'
    })), required=True)
    total_beds = forms.CharField(widget=(forms.TextInput(attrs={
        'class': 'form-control custom_checkbox',
        'type': 'text',
        'placeholder': 'Number of beds'
    })), required=False)
    state = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}),
                              choices=States, initial='MP')

    class Meta:
        model = management_models.Hospitals
        fields = '__all__'


class AddDetails(ModelForm):
    first_name = forms.CharField(widget=(forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
        'placeholder': 'Enter your First Name.'
    })), required=True)
    last_name = forms.CharField(widget=(forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
        'placeholder': 'Enter your Last Name.'
    })), required=True)
    email = forms.CharField(widget=(forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'email',
        'placeholder': 'Enter your email.'
    })), required=False)
    phone = forms.CharField(widget=(forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
        'placeholder': 'Enter your Phone Number.'
    })), required=False)
    city = forms.CharField(widget=(forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
        'placeholder': 'Enter your city.'
    })), required=False)
    blood_group = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}),
                                    choices=BloodGroup, required=False, label="(Select here)")
    specify_other = forms.CharField(widget=(forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
        'placeholder': 'Specify Other.'
    })), required=False)
    additional_details = forms.CharField(widget=(forms.Textarea(attrs={
        'class': 'form-control',
        'rows': 7,
        'placeholder': 'Please add additional details here.'
    })), required=False)
    state = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}),
                              choices=States, initial='MP')

    class Meta:
        model = user_models.User
        fields = '__all__'

templates/frontend/add_hospital.html
{% extends 'frontend/base/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}
{% block page_content %}
    <style>
        input[type=checkbox], input[type=radio] {
            width: auto;
        }

        .pdt-40 {
            padding-top: 40px;
        }
    </style>
    <style>
        .modal-confirm {
            color: #434e65;
            width: 525px;
        }

        .modal-confirm .modal-content {
            padding: 20px;
            font-size: 16px;
            border-radius: 5px;
            border: none;
        }

        .modal-confirm .modal-header {
            background: #47c9a2;
            border-bottom: none;
            position: relative;
            text-align: center;
            margin: -20px -20px 0;
            border-radius: 5px 5px 0 0;
            padding: 35px;
        }

        .modal-confirm h4 {
            text-align: center;
            font-size: 36px;
            margin: 10px 0;
        }

        .modal-confirm .form-control, .modal-confirm .btn {
            min-height: 40px;
            border-radius: 3px;
        }

        .modal-confirm .close {
            position: absolute;
            top: 15px;
            right: 15px;
            color: #fff;
            text-shadow: none;
            opacity: 0.5;
        }

        .modal-confirm .close:hover {
            opacity: 0.8;
        }

        .modal-confirm .icon-box {
            color: #fff;
            width: 95px;
            height: 95px;
            display: inline-block;
            border-radius: 50%;
            z-index: 9;
            border: 5px solid #fff;
            padding: 15px;
            text-align: center;
        }

        .modal-confirm .icon-box i {
            font-size: 64px;
            margin: -4px 0 0 -4px;
        }

        .modal-confirm.modal-dialog {
            margin-top: 80px;
        }

        .modal-confirm .btn, .modal-confirm .btn:active {
            color: #fff;
            border-radius: 4px;
            text-decoration: none;
            transition: all 0.4s;
            line-height: normal;
            border-radius: 30px;
            margin-top: 10px;
            padding: 6px 20px;
            border: none;
        }

        .modal-confirm .btn:hover, .modal-confirm .btn:focus {
            outline: none;
        }

        .modal-confirm .btn span {
            margin: 1px 3px 0;
            float: left;
        }

        .modal-confirm .btn i {
            margin-left: 1px;
            font-size: 20px;
            float: right;
        }

        .trigger-btn {
            display: inline-block;
            margin: 100px auto;
        }
    </style>

    <!-- Modal HTML -->
    <div id="success_modal" data-backdrop="static" data-keyboard="false" class="modal fade">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header justify-content-center">
                    <div>
                        <div class="icon-box">
                            <i class="material-icons">&#xE876;</i>
                        </div>
                    </div>
                </div>
                <div class="modal-body text-center">
                    <h4 class="text-success">Success !!!</h4>
                    <p>Your Hospital details has been added successfully.</p>
                    <a href="{% url 'frontend:index' %}" class="btn btn-success"><span>Go to Home</span> <i
                            class="material-icons">&#xE5C8;</i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- ==========Page Header Section Start Here========== -->
    <section class="page-header-section service-title style-1"
             style="background-image: url({% static 'assets/images/pageheader/pageheader.jpg' %}); width: 100%;">
        <div class="page-header-content">
            <div class="container">
                <div class="page-header-content-inner">
                    <div class="page-title">
                        <h2>Please Fill the Availability Form</h2>
                    </div>
                    <ol class="breadcrumb">
                        <li><a href="{% url 'frontend:index' %}">Home</a></li>
                        <li class="active">Add Details</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <!-- ==========Page Header Section Ends Here========== -->
    <section class="contact-us pt-5">
        <div class="container">
            <div class="section-wrapper">
                <form action="{% url 'frontend:add_hospital' %}" method="post">
                    {% csrf_token %}
                    <div class="row">

                        <div class="col-md-3">
                            <label>Contact Number</label>
                            <div class="form-group">
                                {{ forms.contact_info }}
                            </div>
                            {% if errors.contact_info %}
                                <span class="text-danger">{{ errors.contact_info }}</span>{% endif %}

                        </div>
                        <div class="col-md-3">
                            <label>Hospital Name</label>
                            <div class="form-group">
                                {#                        <input class="form-control" required type="text" placeholder="Enter Hospital Name">#}
                                {{ forms.hospital_name }}
                            </div>
                            {% if errors.hospital_name %}
                                <span class="text-danger">{{ errors.hospital_name }}</span>{% endif %}
                        </div>
                        <div class="col-md-3">
                            <label>State</label>
                            <div class="form-group">
                                {{ forms.state }}
                            </div>
                            {% if errors.state %}<span class="text-danger">{{ errors.state }}</span>{% endif %}

                        </div>
                        <div class="col-md-3">
                            <label>City</label>
                            <div class="form-group">
                                {{ forms.city }}

                            </div>
                            {% if errors.city %}<span class="text-danger">{{ errors.city }}</span>{% endif %}
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="id_total_beds">Total Beds Capacity</label>
                                {{ forms.total_beds }}
                            </div>
                            {% if errors.total_beds %}
                                <span class="text-danger">{{ errors.total_beds }}</span>{% endif %}
                        </div>
                        <div class="col-md-3">
                            <div class="form-group pdt-40">
                                {{ forms.oxygen_availability }}
                                <label for="id_oxygen_availability">Oxygen Available</label>
                            </div>
                            {% if errors.oxygen_availability %}
                                <span class="text-danger">{{ errors.oxygen_availability }}</span>
                            {% endif %}
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="id_total_beds">Total Beds</label>
                                {{ forms.total_beds }}
                            </div>
                            {% if errors.total_beds %}
                                <span class="text-danger">{{ errors.total_beds }}</span>{% endif %}
                        </div>
                        <div class="col-md-3">
                            <div class="form-group pdt-40">
                                {{ forms.oxygen_availability }}
                                <label for="id_oxygen_availability">Oxygen Available</label>
                            </div>
                            {% if errors.oxygen_availability %}
                                <span class="text-danger">{{ errors.oxygen_availability }}</span>{% endif %}

                        </div>
                        <div class="col-md-3">
                            <div class="form-group pdt-40">
                                {{ forms.ventilator_availability }}
                                <label for="ventilator_available">Ventilator Available</label>
                            </div>
                            {% if errors.ventilator_availability %}
                                <span class="text-danger">{{ errors.ventilator_availability }}</span>{% endif %}

                        </div>
                        <div class="col-md-12 text-right">
                            <button class="lab-btn" type="submit"><span>Submit <i
                                    class="icofont-double-right"></i></span></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}
{% block extra_script %}
    <script>
        var success = '{{ success }}';
        $(document).ready(function () {
            if (success === 'true') {
                $('#success_modal').modal({show: true});
            }
        });
    </script>
{% endblock %}

templates/frontend/news.html
{% extends 'frontend/base/base.html' %}
{% load static %}

{% block page_content %}

    {% if data %}
        {% for report in data %}
            {{ report.activeCases }}
        {% endfor %}
    {% endif %}

{% endblock %}

templates/frontend/want_help.html
{% extends 'frontend/base/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        input[type=checkbox], input[type=radio] {
            width: auto;
        }
    </style>
    <style>
        .modal-confirm {
            color: #434e65;
            width: 525px;
        }

        .modal-confirm .modal-content {
            padding: 20px;
            font-size: 16px;
            border-radius: 5px;
            border: none;
        }

        .modal-confirm .modal-header {
            background: #47c9a2;
            border-bottom: none;
            position: relative;
            text-align: center;
            margin: -20px -20px 0;
            border-radius: 5px 5px 0 0;
            padding: 35px;
        }

        .modal-confirm h4 {
            text-align: center;
            font-size: 36px;
            margin: 10px 0;
        }

        .modal-confirm .form-control, .modal-confirm .btn {
            min-height: 40px;
            border-radius: 3px;
        }

        .modal-confirm .close {
            position: absolute;
            top: 15px;
            right: 15px;
            color: #fff;
            text-shadow: none;
            opacity: 0.5;
        }

        .modal-confirm .close:hover {
            opacity: 0.8;
        }

        .modal-confirm .icon-box {
            color: #fff;
            width: 95px;
            height: 95px;
            display: inline-block;
            border-radius: 50%;
            z-index: 9;
            border: 5px solid #fff;
            padding: 15px;
            text-align: center;
        }

        .modal-confirm .icon-box i {
            font-size: 64px;
            margin: -4px 0 0 -4px;
        }

        .modal-confirm.modal-dialog {
            margin-top: 80px;
        }

        .modal-confirm .btn, .modal-confirm .btn:active {
            color: #fff;
            border-radius: 4px;
            text-decoration: none;
            transition: all 0.4s;
            line-height: normal;
            border-radius: 30px;
            margin-top: 10px;
            padding: 6px 20px;
            border: none;
        }

        .modal-confirm .btn:hover, .modal-confirm .btn:focus {
            outline: none;
        }

        .modal-confirm .btn span {
            margin: 1px 3px 0;
            float: left;
        }

        .modal-confirm .btn i {
            margin-left: 1px;
            font-size: 20px;
            float: right;
        }

        .trigger-btn {
            display: inline-block;
            margin: 100px auto;
        }
    </style>
{% endblock %}
{% block page_content %}
    <!-- Modal HTML -->
    <div id="success_modal" data-backdrop="static" data-keyboard="false" class="modal fade">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header justify-content-center">
                    <div>
                        <div class="icon-box">
                            <i class="material-icons">&#xE876;</i>
                        </div>
                    </div>
                </div>
                <div class="modal-body text-center">
                    <h4 class="text-success">Success !!!</h4>
                    <p>Thank you for help.</p>
                    <a href="{% url 'frontend:index' %}" class="btn btn-success"><span>Go to Home</span> <i
                            class="material-icons">&#xE5C8;</i></a>
                </div>
            </div>
        </div>
    </div>

    <!-- ==========Page Header Section Start Here========== -->
    <section class="page-header-section service-title style-1"
             style="background-image: url({% static 'assets/images/pageheader/pageheader.jpg' %}); width: 100%;">
        <div class="page-header-content">
            <div class="container">
                <div class="page-header-content-inner">
                    <div class="page-title">
                        <h2>I Want to Help for...</h2>
                    </div>
                    <ol class="breadcrumb">
                        <li><a href="{% url 'frontend:index' %}">Home</a></li>
                        <li class="active">Add Availabilities</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <!-- ==========Page Header Section Ends Here========== -->
    <section class="contact-us pt-5">
        <div class="container">
            <div class="section-wrapper">
                <form method="post" action="{% url 'frontend:want_help' %}">
                    {% csrf_token %}
                    <div class="row">
                        {#                <div class="col-md-12">#}
                        {#                    <h3 class="alert alert-info">Add Details</h3>#}
                        {#                </div>#}
                        <div class="col-md-4">
                            <label>First Name/ Organization</label>
                            <div class="form-group">
                                {{ forms.first_name }}
                                {% if  errors.first_name %}<p class="text-danger">{{ errors.first_name }}{% endif %}</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label>Last Name</label>
                            <div class="form-group">
                                {{ forms.last_name }}
                                {% if  errors.last_name %}<p class="text-danger">{{ errors.last_name }}{% endif %}</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label>Email</label>
                            <div class="form-group">
                                {{ forms.email }}
                                {% if  errors.email %}<p class="text-danger">{{ errors.email }}{% endif %}</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label>Phone</label>
                            <div class="form-group">
                                {{ forms.phone }}
                                {% if  errors.phone %}<p class="text-danger">{{ errors.phone }}{% endif %}</p>

                            </div>
                        </div>
                        <div class="col-md-4">
                            <label>State</label>
                            <div class="form-group">
                                {{ forms.state }}
                                {% if  errors.state %}<p class="text-danger">{{ errors.state }}{% endif %}</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label>City / PAN</label>
                            <div class="form-group">
                                {{ forms.city }}
                                {% if  errors.city %}<p class="text-danger">{{ errors.city }}{% endif %}</p>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <label class="text-primary">Please select One or the more from </label>
                        </div>

                        <div class="col-md-3">
                            <div class="form-group">
                                {{ forms.oxygen_cylinder_supplier }}
                                <label for="id_oxygen_cylinder_supplier">Oxygen Cylinder</label>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                {{ forms.plasma_donor }}
                                <label for="id_plasma_donor">Plasma Donor</label>
                            </div>
                            <div class="border-info border p-2" id="plasmadoner_body">
                                <div class="form-group">
                                    <label>Blood Group</label>
                                    {{ forms.blood_group }}
                                </div>
                            </div>
                            <br/>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                {{ forms.medical_supplier }}
                                <label for="id_medical_supplier">Medical Supply</label>
                            </div>
                            <div class="border-info border p-2" id="madical_supply_body">
                                <div class="form-group">
                                    {{ forms.remdisivr }}
                                    <label for="id_remdisivr">Remdisvir</label>
                                </div>
                                <div class="form-group">
                                    {{ forms.toclizumab }}
                                    <label for="id_toclizumab">Tocilizumab</label>
                                </div>
                                <div class="form-group">
                                    <input id="other" type="checkbox" style="width: auto;">
                                    <label for="other">Other</label>
                                    <div id="other_medical_body">
                                        {{ forms.specify_other }}
                                    </div>
                                </div>
                            </div>
                            <br/>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                {{ forms.medical_support }}
                                <label for="id_medical_support">Medical Help</label>
                            </div>
                            <div class="border-info border p-2 " id="medical_help_body">

                                <div class="form-group">
                                    {{ forms.doctor }}
                                    <label for="id_doctor">Doctor</label>
                                </div>
                                <div class="form-group">
                                    {{ forms.health_care_worker }}
                                    <label for="id_health_care_worker">HealthCare Worker</label>
                                </div>
                            </div>
                            <br/>
                        </div>
                        <div class="col-md-12">
                            <label>Additional Details</label>
                            {{ forms.additional_details }}
                        </div>
                        <div class="col-md-12 text-right">
                            <button class="lab-btn" type="submit"><span>Submit <i
                                            class="icofont-double-right"></i></span></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}
{% block extra_script %}
    <script>
        $(function () {
            $("#plasmadoner_body").hide();
            $("#madical_supply_body").hide();
            $("#other_medical_body").hide();
            $("#medical_help_body").hide();

            $("#id_plasma_donor").click(function () {
                if ($(this).is(":checked")) {
                    $("#plasmadoner_body").show();
                } else {
                    $("#id_blood_group").val("");
                    $("#plasmadoner_body").hide();
                }
            });

            $("#id_medical_supplier").click(function () {
                if ($(this).is(":checked")) {
                    $("#madical_supply_body").show();
                } else {
                    $('#id_remdisivr').prop('checked', false);
                    $('#id_toclizumab').prop('checked', false);
                    $('#other').prop('checked', false);
                    $("#id_specify_other").val("");
                    $("#madical_supply_body").hide();
                    $("#other_medical_body").hide();
                }
            });
            $("#other").click(function () {
                if ($(this).is(":checked")) {
                    $("#other_medical_body").show();
                } else {
                    $("#id_specify_other").val("");
                    $("#other_medical_body").hide();
                }
            });
            $("#id_medical_support").click(function () {
                if ($(this).is(":checked")) {
                    $("#medical_help_body").show();
                } else {
                    $('#id_id_doctor').prop('checked', false);
                    $('#id_health_care_worker').prop('checked', false);
                    $("#medical_help_body").hide();
                }
            });

        });
    </script>
    <script>
        var success = '{{ success }}';
        $(document).ready(function () {
            if (success === 'true') {
                $('#success_modal').modal({show: true});
            }
        });
    </script>
{% endblock %}