healthCareManagment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('management.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

management/urls.py
from django.urls import path

from . import views
app_name = 'frontend'
urlpatterns = [
    path('', views.home, name='index'),
    path('about-us/', views.about_us, name='about_us'),
    path('news/', views.latest_news, name='latest_news'),
    path('help/', views.WantHelp, name='want_help'),
    path('add/hospital/', views.add_hospital, name='add_hospital'),
    path('list/', views.medical_list, name='medical_list'),
    path('filter/', views.user_filter, name='user_filter'),
    path('filter-list/<str:pk>', views.filter_list, name='filter_list'),
    path('plasma/<str:pk>', views.blood_group, name='plasma'),
    path('custom-news-job', views.custom_news_job, name='news_job')
]

user/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/frontend/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
 <meta name="description" content="Your Helping Hand">
  <meta name="keywords" content="Covid-19,covid19, want to help,want to help in covid, medical, help, corona, cylinder, ventilator, beds available, mp beds available, plasma">
  <meta name="author" content="yourhealpinghand.in">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com/">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap"
            rel="stylesheet">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/images/logo/logo.png' %}">
    <!-- Other css -->
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/icofont.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/swiper.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/hc-offcanvas-nav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block extra_css %}{% endblock %}


    <title>Your Helping Hands</title>
    <style>
        .right_nav {
            text-align: right;
        }

        .right_nav > li {
            display: inline-block;
        }
        .footer-bottom{
            padding: 30px 20px;
            border: 1px solid #ddd;
        }
        .footer-bottom span>a{
            color: #c73c31;
            font-weight: 600;
        }
        .main-menu li a{
            padding: 0;
        }
        .nav-padding{
            padding: 25px 15px
        }
    </style>
</head>

<body>
<!-- preloader start here -->
<div class="preloader">
    <div class="preloader-inner">
        <div class="preloader-icon">
            <span></span>
            <span></span>
        </div>
    </div>
</div>
<!-- preloader ending here -->


<!-- ========== Mobile-nav section start here ========== -->
<div class="mobile-menu">
    <div class="container">
        <div class="mobile-menu-wrapper">
            <div class="logo">
                <a href="{% url 'frontend:index' %}">
                    <img src="{% static 'assets/images/logo/logo.png' %}" style="width:50px" alt="">
                </a>
            </div>
            <div class="open-menu"><i class="icofont-navigation-menu"></i></div>
        </div>
        <nav id="mobile-nav">
            <ul class="home-nav">
                <li class="home">
                    <a href="{% url 'frontend:index' %}">Home</a>
                </li>
            </ul>
            <ul class="depart-nav">
                <li class="depart">
                    <a href="{% url 'frontend:add_hospital' %}">Hospital</a>
                </li>
            </ul>
{#            <ul class="depart-nav">#}
{#                <li class="depart">#}
{#                    <a href="{% url 'frontend:about_us' %}">About Us</a>#}
{#                </li>#}
{#            </ul>#}
            <ul class="depart-nav">
                <li class="depart">
                    <a href="{% url 'frontend:latest_news' %}">News</a>
                </li>
            </ul>

        </nav>
    </div>
</div>
<!-- ========== Mobile-nav section end here ========== -->


<!-- ==========Header Section Starts Here========== -->
<header class="header-section d-none d-lg-block">
    <div class="header-bottom">
        <nav class="container">
            <div class="primary-menu">
                <div class="menu-area">

                    <div class="">
                        <ul class="main-menu right_nav nav-padding" style="justify-content: flex-end;">
                            <li style="float: left;">
                                <a href="{% url 'frontend:index' %}">
                                    <img src="{% static 'assets/images/logo/logo.png' %}" style="width: 50px;" alt="">
                                </a>

                            </li>
                            <li class="active">
                                <a href="{% url 'frontend:index' %}">Home</a>

                            </li>
                            <li>
                                <a href="{% url 'frontend:add_hospital' %}"> Hospital</a>
                            </li>
{#                            <li>#}
{#                                <a href="{% url 'frontend:about_us' %}"> About Us</a>#}
{#                            </li>#}
                            <li>
                                <a href="{% url 'frontend:latest_news' %}">News</a>

                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</header>
<!-- ==========Header Section Ends Here========== -->



{% block page_content %}
{% endblock %}


<!-- ==========Footer Section Ends Here========== -->
<div class="footer-bottom mt-5">
    <div class="copyright text-center wow fadeInUp" data-wow-duration="1s" data-wow-delay=".1s">
        <span>Copyright &copy; 2021 <a href="{% url 'frontend:index' %}">YourHelpingHands</a></span>.
    </div>
</div>
<!-- ==========Footer Section Ends Here========== -->

<!-- scrollToTop start here -->
<a href="#" class="scrollToTop"><i class="icofont-rounded-up"></i></a>
<!-- scrollToTop ending here -->


<!-- All Scripts -->
<script src="{% static 'assets/js/jquery.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/waypoints.min.js' %}"></script>
<script src="{% static 'assets/js/swiper.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'assets/js/wow.min.js' %}"></script>
<script src="{% static 'assets/js/circularProgressBar.min.js' %}"></script>
<script src="{% static 'assets/js/hc-offcanvas-nav.js' %}"></script>
<script src="{% static 'assets/js/functions.js' %}"></script>
{% block extra_script %}{% endblock %}
</body>
</html>